# Usa una imagen base de nginx para servir contenido estático
FROM nginx:alpine
# Copia los archivos estáticos al directorio de nginx
COPY ./static /usr/share/nginx/html
# Expone el puerto 80
EXPOSE 80

